#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Auto-generated by setup-autostart.sh (extended with mount persistence).
# Resume all NemoClaw sandboxes after the gateway container starts, then
# re-mount each one via SSHFS so workspace files are accessible locally.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SANDBOXES_FILE="${HOME}/.nemoclaw/sandboxes.json"
RESUMED=0
FAILED=0
POST_RESUME_SYNC_SCRIPT="${NEMOCLAW_POST_RESUME_SYNC_SCRIPT:-${HOME}/dev/merc/agentic-foundry/agents/nemoclaw/sync.sh}"

log() { echo "$(date '+%H:%M:%S') [nemoclaw-autostart] $*"; }

if [[ ! -f "${SANDBOXES_FILE}" ]]; then
  log "No sandboxes registry found at ${SANDBOXES_FILE}"
  exit 0
fi

while IFS= read -r name; do
  [[ -z "${name}" ]] && continue
  log "Resuming sandbox '${name}'..."
  if bash "${SCRIPT_DIR}/resume.sh" "${name}"; then
    if [[ "${name}" == "cortana" ]] && [[ -x "${POST_RESUME_SYNC_SCRIPT}" ]]; then
      log "  ↻ running post-resume sync for '${name}'..."
      if bash "${POST_RESUME_SYNC_SCRIPT}"; then
        log "  ✓ post-resume sync applied"
      else
        log "  ✗ post-resume sync failed"
        FAILED=$((FAILED + 1))
        continue
      fi
    fi
    log "  ✓ ${name} resumed"
    RESUMED=$((RESUMED + 1))
  else
    log "  ✗ ${name} resume failed (check: nemoclaw ${name} status)"
    FAILED=$((FAILED + 1))
  fi
done < <(python3 -c "
import json, sys
d = json.load(open('${SANDBOXES_FILE}'))
sbs = d.get('sandboxes', {})
if isinstance(sbs, dict):
    for sb in sbs.values(): print(sb.get('name',''))
else:
    for sb in sbs: print(sb.get('name',''))
" 2>/dev/null || true)

log "Done: ${RESUMED} resumed, ${FAILED} failed"
[[ "${FAILED}" -eq 0 ]]
