#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Auto-generated by setup-autostart.sh — do not edit by hand.
# Resume all NemoClaw sandboxes after the gateway container starts.
set -euo pipefail

# shellcheck disable=SC2139
NEMOCLAW_CMD="node /home/mindseye/dev/merc/NemoClaw/bin/nemoclaw.js"
MAX_GATEWAY_WAIT=120
POLL_INTERVAL=3

log() { echo "$(date '+%H:%M:%S') [nemoclaw-autostart] $*"; }

nemoclaw_run() {
  # Supports both "nemoclaw" and "node /path/to/nemoclaw.js" forms
  # shellcheck disable=SC2086
  ${NEMOCLAW_CMD} "$@"
}

# Wait for the gateway container to come up
log "Waiting for gateway to become ready..."
for i in $(seq 1 $((MAX_GATEWAY_WAIT / POLL_INTERVAL))); do
  if openshell gateway info >/dev/null 2>&1; then
    log "Gateway ready"
    break
  fi
  if [[ "$i" -eq $((MAX_GATEWAY_WAIT / POLL_INTERVAL)) ]]; then
    log "ERROR: Gateway did not become ready within ${MAX_GATEWAY_WAIT}s"
    exit 1
  fi
  sleep "${POLL_INTERVAL}"
done

# Resume each sandbox in the registry
SANDBOXES_FILE="${HOME}/.nemoclaw/sandboxes.json"
RESUMED=0
FAILED=0

if [[ -f "${SANDBOXES_FILE}" ]]; then
  while IFS= read -r name; do
    [[ -z "${name}" ]] && continue
    log "Resuming sandbox '${name}'..."
    if nemoclaw_run "${name}" resume; then
      log "  ✓ ${name} resumed"
      RESUMED=$((RESUMED + 1))
    else
      log "  ✗ ${name} resume failed (check: nemoclaw ${name} status)"
      FAILED=$((FAILED + 1))
    fi
  done < <(python3 -c "
import json, sys
d = json.load(open('${SANDBOXES_FILE}'))
sbs = d.get('sandboxes', {})
if isinstance(sbs, dict):
    for sb in sbs.values(): print(sb.get('name',''))
else:
    for sb in sbs: print(sb.get('name',''))
" 2>/dev/null || true)
fi

log "Done: ${RESUMED} resumed, ${FAILED} failed"
[[ "${FAILED}" -eq 0 ]]
