#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# setup-autostart.sh — Create a systemd user service that fully restores NemoClaw
# after a reboot: sets Docker restart policy on the gateway, then resumes all
# registered sandboxes once the gateway is back up.
#
# What it does:
#   1. Sets Docker restart policy to 'unless-stopped' on the gateway container.
#   2. Writes ~/.config/systemd/user/nemoclaw-autostart.service
#   3. Enables + starts the service so sandboxes are resumed on next login/boot.
#
# Requirements:
#   - systemd (Linux only)
#   - Docker running (gateway container must already exist)
#   - nemoclaw installed (npm link or local shim)
#   - loginctl enable-linger <user> must be set for boot-time startup
#     (the script offers to enable it)
#
# Usage:
#   bash scripts/setup-autostart.sh
#   bash scripts/setup-autostart.sh --uninstall

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NEMOCLAW_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

SERVICE_NAME="nemoclaw-autostart"
SERVICE_FILE="${HOME}/.config/systemd/user/${SERVICE_NAME}.service"
RESUME_SCRIPT="${NEMOCLAW_ROOT}/scripts/resume-all-sandboxes.sh"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info() { echo -e "${CYAN}  ▸${NC} $*"; }
ok() { echo -e "${GREEN}  ✓${NC} $*"; }
warn() { echo -e "${YELLOW}  ⚠${NC} $*"; }
fatal() {
  echo -e "${RED}  ✗${NC} $*" >&2
  exit 1
}

# ── Uninstall ──────────────────────────────────────────────────────────────────
if [[ "${1:-}" == "--uninstall" ]]; then
  echo ""
  echo "  Removing NemoClaw autostart..."
  systemctl --user stop "${SERVICE_NAME}" 2>/dev/null || true
  systemctl --user disable "${SERVICE_NAME}" 2>/dev/null || true
  rm -f "${SERVICE_FILE}" "${RESUME_SCRIPT}"
  systemctl --user daemon-reload 2>/dev/null || true
  ok "Autostart removed"
  echo ""
  exit 0
fi

echo ""
echo -e "  ${CYAN}NemoClaw Autostart Setup${NC}"
echo "  ══════════════════════════════════════════════"
echo ""

# ── Verify systemd is available ────────────────────────────────────────────────
command -v systemctl >/dev/null 2>&1 \
  || fatal "systemctl not found. This script requires systemd (Linux only)."

systemctl --user status >/dev/null 2>&1 \
  || fatal "systemd --user is not available. Ensure your session has a user bus (pam_systemd)."

# ── Verify Docker is available ─────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 \
  || fatal "docker not found. Install Docker first."

# ── Find gateway container ─────────────────────────────────────────────────────
GATEWAY_NAME=$(openshell gateway info 2>&1 | grep -oP 'Gateway:\s+\K\S+' || echo "nemoclaw")
GATEWAY_CTR="openshell-cluster-${GATEWAY_NAME}"

if ! docker inspect "${GATEWAY_CTR}" >/dev/null 2>&1; then
  fatal "Gateway container '${GATEWAY_CTR}' not found. Run 'nemoclaw start' first."
fi

# ── Step 1: Docker restart policy ─────────────────────────────────────────────
info "Setting Docker restart policy to 'unless-stopped' on '${GATEWAY_CTR}'..."
if docker update --restart=unless-stopped "${GATEWAY_CTR}"; then
  ok "Restart policy set — gateway will auto-start with Docker"
else
  warn "Could not update restart policy (non-fatal)"
fi

# ── Step 2: Discover registered sandboxes ─────────────────────────────────────
SANDBOXES_FILE="${HOME}/.nemoclaw/sandboxes.json"
SANDBOX_LIST=()

if [[ -f "${SANDBOXES_FILE}" ]]; then
  while IFS= read -r name; do
    [[ -n "${name}" ]] && SANDBOX_LIST+=("${name}")
  done < <(python3 -c "
import json, sys
d = json.load(open('${SANDBOXES_FILE}'))
for sb in d.get('sandboxes', []):
    print(sb.get('name',''))
" 2>/dev/null || true)
fi

if [[ ${#SANDBOX_LIST[@]} -eq 0 ]]; then
  warn "No sandboxes found in ${SANDBOXES_FILE}. The service will resume whatever is registered at boot time."
else
  info "Sandboxes to resume: ${SANDBOX_LIST[*]}"
fi

# ── Step 3: Find nemoclaw binary ───────────────────────────────────────────────
NEMOCLAW_BIN="$(command -v nemoclaw 2>/dev/null || true)"
if [[ -z "${NEMOCLAW_BIN}" ]]; then
  # Try npm global bin
  NEMOCLAW_BIN="$(npm bin -g 2>/dev/null)/nemoclaw"
  [[ -x "${NEMOCLAW_BIN}" ]] || fatal "nemoclaw binary not found. Run 'npm link' from the NemoClaw directory."
fi
info "nemoclaw binary: ${NEMOCLAW_BIN}"

# ── Step 4: Write resume-all-sandboxes.sh helper ──────────────────────────────
info "Writing resume helper: ${RESUME_SCRIPT}"
cat >"${RESUME_SCRIPT}" <<RESUME_SCRIPT_CONTENT
#!/usr/bin/env bash
# Auto-generated by setup-autostart.sh — do not edit by hand.
# Resume all NemoClaw sandboxes after the gateway container starts.
set -euo pipefail

NEMOCLAW="${NEMOCLAW_BIN}"
MAX_GATEWAY_WAIT=120
POLL_INTERVAL=3

log() { echo "\$(date '+%H:%M:%S') [nemoclaw-autostart] \$*"; }

# Wait for the gateway container to come up
log "Waiting for gateway to become ready..."
for i in \$(seq 1 \$((MAX_GATEWAY_WAIT / POLL_INTERVAL))); do
  if openshell gateway info >/dev/null 2>&1; then
    log "Gateway ready"
    break
  fi
  if [[ "\$i" -eq \$((MAX_GATEWAY_WAIT / POLL_INTERVAL)) ]]; then
    log "ERROR: Gateway did not become ready within \${MAX_GATEWAY_WAIT}s"
    exit 1
  fi
  sleep "\${POLL_INTERVAL}"
done

# Resume each sandbox in the registry
SANDBOXES_FILE="\${HOME}/.nemoclaw/sandboxes.json"
RESUMED=0
FAILED=0

if [[ -f "\${SANDBOXES_FILE}" ]]; then
  while IFS= read -r name; do
    [[ -z "\${name}" ]] && continue
    log "Resuming sandbox '\${name}'..."
    if "\${NEMOCLAW}" "\${name}" resume; then
      log "  ✓ \${name} resumed"
      RESUMED=\$((RESUMED + 1))
    else
      log "  ✗ \${name} resume failed (check: nemoclaw \${name} status)"
      FAILED=\$((FAILED + 1))
    fi
  done < <(python3 -c "
import json, sys
d = json.load(open('\${SANDBOXES_FILE}'))
for sb in d.get('sandboxes', []):
    print(sb.get('name',''))
" 2>/dev/null || true)
fi

log "Done: \${RESUMED} resumed, \${FAILED} failed"
[[ "\${FAILED}" -eq 0 ]]
RESUME_SCRIPT_CONTENT

chmod +x "${RESUME_SCRIPT}"
ok "Resume helper written"

# ── Step 5: Write systemd user service ────────────────────────────────────────
info "Writing systemd user service: ${SERVICE_FILE}"
mkdir -p "$(dirname "${SERVICE_FILE}")"

cat >"${SERVICE_FILE}" <<SERVICE_CONTENT
[Unit]
Description=NemoClaw Sandbox Autostart
Documentation=https://www.nvidia.com/nemoclaw
# Wait for Docker to be fully available before starting
After=docker.service network-online.target
# If Docker is a user socket (e.g., Colima), omit the system unit dependency;
# the resume script will poll until the gateway is ready regardless.
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=${RESUME_SCRIPT}
# Restart if the script fails (e.g., Docker was slow)
Restart=on-failure
RestartSec=10
# Give Docker + k3s + sandboxes time to fully start
TimeoutStartSec=180
# Environment for nemoclaw / openshell
Environment=HOME=${HOME}
Environment=PATH=${PATH}

[Install]
WantedBy=default.target
SERVICE_CONTENT

ok "Service file written"

# ── Step 6: Enable service ─────────────────────────────────────────────────────
info "Enabling and starting service..."
systemctl --user daemon-reload
systemctl --user enable "${SERVICE_NAME}"
systemctl --user start "${SERVICE_NAME}" || true # may fail now if Docker isn't ready — that's ok

ok "Service enabled: ${SERVICE_NAME}"

# ── Step 7: Check linger (required for auto-start at boot without login) ───────
echo ""
if loginctl show-user "$(whoami)" 2>/dev/null | grep -q "Linger=yes"; then
  ok "Linger already enabled — service will start at boot even without login"
else
  warn "Linger is not enabled. Without it, the service only runs after you log in."
  echo ""
  echo -e "  Enable it now? (requires sudo)"
  read -r -p "  > sudo loginctl enable-linger $(whoami)  [y/N] " yn
  if [[ "${yn,,}" == "y" ]]; then
    sudo loginctl enable-linger "$(whoami)"
    ok "Linger enabled — service will now start at boot"
  else
    echo ""
    info "Run this manually when ready:"
    echo "    sudo loginctl enable-linger $(whoami)"
  fi
fi

# ── Summary ────────────────────────────────────────────────────────────────────
echo ""
echo "  ══════════════════════════════════════════════"
echo -e "  ${GREEN}Autostart configured.${NC}"
echo ""
echo "  After reboot:"
echo "    • Docker restarts '${GATEWAY_CTR}' automatically"
echo "    • systemd resumes all registered sandboxes"
echo ""
echo "  Manage it:"
echo "    systemctl --user status  ${SERVICE_NAME}"
echo "    systemctl --user restart ${SERVICE_NAME}"
echo "    journalctl --user -u ${SERVICE_NAME} -f"
echo "    bash scripts/setup-autostart.sh --uninstall"
echo ""
